name: Test git-age

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        #os: [windows-latest, ubuntu-latest, macos-latest]
        #encryption_type: [symmetric, asymmetric]
        os: [windows-latest]
        encryption_type: [symmetric]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test encryption and decryption
        shell: bash
        run: |
          echo "RUNNER_OS: $RUNNER_OS"
          echo "MSYSTEM: $MSYSTEM"
          echo "uname -s: $(uname -s)"
          echo "uname -o: $(uname -o)"
          . ./test/git-age-test.sh
          install_age
          test_encryption ${{ matrix.encryption_type }}
          test_decryption ${{ matrix.encryption_type }}
