name: Test git-age

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux-symmetric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test encryption and decryption
        run: |
          source ./test/git-age-test.sh
          install_age
          test_encryption symmetric
          test_decryption symmetric

  test-linux-asymmetric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install age
        run: |
          source ./test/git-age-test.sh
          install_age
          test_encryption asymmetric
          test_decryption asymmetric
  
  test-windows-symmetric:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test encryption and decryption
        run: |
          source ./test/git-age-test.sh
          install_age
          test_encryption symmetric
          test_decryption symmetric
  
  test-windows-symmetric:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test encryption and decryption
        run: |
          source ./test/git-age-test.sh
          install_age
          test_encryption asymmetric
          test_decryption asymmetric
  
  test-macos-symmetric:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test encryption and decryption
        run: |
          source ./test/git-age-test.sh
          install_age
          test_encryption symmetric
          test_decryption symmetric

  test-macos-asymmetric:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test encryption and decryption
        run: |
          source ./test/git-age-test.sh
          install_age
          test_encryption asymmetric
          test_decryption asymmetric
